name: GCC for ARM build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      GCC_VERSION: '9-2019-q4'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - uses: actions/setup-node@v2-beta
      with:
          node-version: 'v12'

    - name: Restore ARM GCC Cache
      id: arm-gcc-cache
      uses: actions/cache@v2
      with:
        path: arm-gcc
        key:  ${{ runner.os }}-arm-gcc-${{ env.GCC_VERSION }}
    - name: Install ARM GCC
      if: steps.arm-gcc-cache.outputs.cache-hit != 'true'
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: ${{ env.GCC_VERSION }}
        directory: arm-gcc
    - name: set PATH
      run: echo "${{ github.workspace }}/arm-gcc/bin" >> $GITHUB_PATH

    - name: make
      run: make

    - name: Upload action artifacts
      uses: actions/upload-artifact@v1
      with:
        name: f030.elf
        path: built/f030/binary.elf
